[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  GITHUB_USERNAME = "mattmcmanus"
  GITHUB_REPO = "mattmcmanus.github.io"
  MICROPUB_TOKEN_ENDPOINT = "https://tokens.indieauth.com/token"
  MICROPUB_ME_URL = "https://mcmanus.io/"